#!/bin/bash

if ! test -d .git; then
    echo "Execute git_hooks_scripts/install-git-hooks in the top-level directory."
    exit 1
fi

mkdir -p .git/hooks

ln -sf ../../git_hooks_scripts/pre-commit.hook .git/hooks/pre-commit || exit 1
chmod +x .git/hooks/pre-commit

touch .git/hooks/applied || exit 1

cp git_hooks_scripts/.clang-format ./

echo
echo "Git hooks are installed successfully."
